import { useRef } from 'react'

interface ProjectInputPanelProps {
  draftJson: string
  error: string | null
  isDirty: boolean
  projectTitle: string
  onDraftChange: (value: string) => void
  onApplyJson: () => void
  onLoadSample: () => void
  onImportFile: (file: File) => void
  onExportJson: () => void
}

function ActionButton({
  label,
  onClick,
  strong = false,
}: {
  label: string
  onClick: () => void
  strong?: boolean
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`rounded-full border px-4 py-2 text-sm font-medium transition hover:-translate-y-0.5 ${
        strong
          ? 'border-sky-400/40 bg-sky-400/16 text-sky-100'
          : 'border-white/10 bg-white/6 text-slate-100 hover:border-white/18'
      }`}
    >
      {label}
    </button>
  )
}

export function ProjectInputPanel({
  draftJson,
  error,
  isDirty,
  projectTitle,
  onDraftChange,
  onApplyJson,
  onLoadSample,
  onImportFile,
  onExportJson,
}: ProjectInputPanelProps) {
  const fileInputRef = useRef<HTMLInputElement | null>(null)

  return (
    <section className="rounded-[30px] border border-white/10 bg-slate-950/50 p-5 backdrop-blur">
      <div className="flex flex-wrap items-start gap-3">
        <div>
          <h2 className="m-0 text-lg font-semibold text-slate-50">Project JSON</h2>
          <p className="mt-1 text-sm text-slate-400">
            Paste the `ProjectDocument` generated by Codex, or load the bundled sample.
          </p>
        </div>
        <div className="ml-auto flex flex-wrap gap-2">
          <ActionButton label="Apply JSON" onClick={onApplyJson} strong />
          <ActionButton label="Load Sample" onClick={onLoadSample} />
          <ActionButton
            label="Import JSON File"
            onClick={() => {
              fileInputRef.current?.click()
            }}
          />
          <ActionButton label="Export JSON" onClick={onExportJson} />
        </div>
      </div>
      <div className="mt-4 flex items-center justify-between text-xs text-slate-400">
        <span>{projectTitle}</span>
        <span>{isDirty ? 'Draft differs from current project' : 'Draft is synced'}</span>
      </div>
      <textarea
        className="scrollbar-thin mt-4 min-h-[320px] w-full rounded-[26px] border border-white/10 bg-[#060b17] p-4 font-editor text-sm text-slate-100 outline-none transition focus:border-sky-400/30"
        value={draftJson}
        onChange={(event) => onDraftChange(event.target.value)}
      />
      {error ? <div className="mt-3 text-sm text-rose-300">{error}</div> : null}
      <input
        ref={fileInputRef}
        type="file"
        accept="application/json,.json"
        className="hidden"
        onChange={(event) => {
          const file = event.target.files?.[0]
          if (file) {
            onImportFile(file)
          }
          event.target.value = ''
        }}
      />
    </section>
  )
}
